baseurl: ''
include: ['_pages']
exclude: ['README.md', 'node_modules', 'gulpfile.js', 'package.json']
includes_dir: ./_components
data_dir: ./_components

moderated: true # false, true
youtubeChannel: 'https://www.youtube.com/channel/UCNyBkSoSBTqv2zctYjfI0hA'
youtubeVideo: 'IGc4aFjv8os'
moderatedUrl: 'http://go4slots.com/go/22rL?'
